# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service/user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user_service/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17user_service/user.proto\x12\x0cuser_service\"H\n\x13RegisterUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"7\n\x14RegisterUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\":\n\x17\x41uthenticateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"J\n\x18\x41uthenticateUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"(\n\x15GetUserProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"^\n\x16GetUserProfileResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t2\xa4\x02\n\x0bUserService\x12U\n\x0cRegisterUser\x12!.user_service.RegisterUserRequest\x1a\".user_service.RegisterUserResponse\x12\x61\n\x10\x41uthenticateUser\x12%.user_service.AuthenticateUserRequest\x1a&.user_service.AuthenticateUserResponse\x12[\n\x0eGetUserProfile\x12#.user_service.GetUserProfileRequest\x1a$.user_service.GetUserProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERUSERREQUEST']._serialized_start=41
  _globals['_REGISTERUSERREQUEST']._serialized_end=113
  _globals['_REGISTERUSERRESPONSE']._serialized_start=115
  _globals['_REGISTERUSERRESPONSE']._serialized_end=170
  _globals['_AUTHENTICATEUSERREQUEST']._serialized_start=172
  _globals['_AUTHENTICATEUSERREQUEST']._serialized_end=230
  _globals['_AUTHENTICATEUSERRESPONSE']._serialized_start=232
  _globals['_AUTHENTICATEUSERRESPONSE']._serialized_end=306
  _globals['_GETUSERPROFILEREQUEST']._serialized_start=308
  _globals['_GETUSERPROFILEREQUEST']._serialized_end=348
  _globals['_GETUSERPROFILERESPONSE']._serialized_start=350
  _globals['_GETUSERPROFILERESPONSE']._serialized_end=444
  _globals['_USERSERVICE']._serialized_start=447
  _globals['_USERSERVICE']._serialized_end=739
# @@protoc_insertion_point(module_scope)
