# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_service/transaction.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction_service/transaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%transaction_service/transaction.proto\x12\x13transaction_service\"~\n\x15\x41\x64\x64TransactionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x0f\n\x07tx_type\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\"@\n\x16\x41\x64\x64TransactionResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"O\n\x16GetTransactionsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\"\x80\x01\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x0f\n\x07tx_type\x18\x05 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t\"Q\n\x17GetTransactionsResponse\x12\x36\n\x0ctransactions\x18\x01 \x03(\x0b\x32 .transaction_service.Transaction2\xed\x01\n\x12TransactionService\x12i\n\x0e\x41\x64\x64Transaction\x12*.transaction_service.AddTransactionRequest\x1a+.transaction_service.AddTransactionResponse\x12l\n\x0fGetTransactions\x12+.transaction_service.GetTransactionsRequest\x1a,.transaction_service.GetTransactionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_service.transaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDTRANSACTIONREQUEST']._serialized_start=62
  _globals['_ADDTRANSACTIONREQUEST']._serialized_end=188
  _globals['_ADDTRANSACTIONRESPONSE']._serialized_start=190
  _globals['_ADDTRANSACTIONRESPONSE']._serialized_end=254
  _globals['_GETTRANSACTIONSREQUEST']._serialized_start=256
  _globals['_GETTRANSACTIONSREQUEST']._serialized_end=335
  _globals['_TRANSACTION']._serialized_start=338
  _globals['_TRANSACTION']._serialized_end=466
  _globals['_GETTRANSACTIONSRESPONSE']._serialized_start=468
  _globals['_GETTRANSACTIONSRESPONSE']._serialized_end=549
  _globals['_TRANSACTIONSERVICE']._serialized_start=552
  _globals['_TRANSACTIONSERVICE']._serialized_end=789
# @@protoc_insertion_point(module_scope)
