# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: report_service/report.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'report_service/report.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1breport_service/report.proto\x12\x0ereport_service\"L\n\x1cGenerateMonthlyReportRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05\x12\r\n\x05month\x18\x03 \x01(\x05\"D\n\x0f\x43\x61tegorySummary\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x0e\n\x06income\x18\x02 \x01(\x01\x12\x0f\n\x07\x65xpense\x18\x03 \x01(\x01\"\xb0\x01\n\rMonthlyReport\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05\x12\r\n\x05month\x18\x03 \x01(\x05\x12\x14\n\x0ctotal_income\x18\x04 \x01(\x01\x12\x15\n\rtotal_expense\x18\x05 \x01(\x01\x12\x0f\n\x07\x62\x61lance\x18\x06 \x01(\x01\x12\x33\n\ncategories\x18\x07 \x03(\x0b\x32\x1f.report_service.CategorySummary\"N\n\x1dGenerateMonthlyReportResponse\x12-\n\x06report\x18\x01 \x01(\x0b\x32\x1d.report_service.MonthlyReport\"S\n\x13\x45xportReportRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05\x12\r\n\x05month\x18\x03 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x04 \x01(\t\"8\n\x14\x45xportReportResponse\x12\x10\n\x08\x66ile_url\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"-\n\x15MsgPackReportResponse\x12\x14\n\x0cmsgpack_data\x18\x01 \x01(\x0c\x32\xd0\x02\n\rReportService\x12t\n\x15GenerateMonthlyReport\x12,.report_service.GenerateMonthlyReportRequest\x1a-.report_service.GenerateMonthlyReportResponse\x12Y\n\x0c\x45xportReport\x12#.report_service.ExportReportRequest\x1a$.report_service.ExportReportResponse\x12n\n\x17GetMonthlyReportMsgPack\x12,.report_service.GenerateMonthlyReportRequest\x1a%.report_service.MsgPackReportResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'report_service.report_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEMONTHLYREPORTREQUEST']._serialized_start=47
  _globals['_GENERATEMONTHLYREPORTREQUEST']._serialized_end=123
  _globals['_CATEGORYSUMMARY']._serialized_start=125
  _globals['_CATEGORYSUMMARY']._serialized_end=193
  _globals['_MONTHLYREPORT']._serialized_start=196
  _globals['_MONTHLYREPORT']._serialized_end=372
  _globals['_GENERATEMONTHLYREPORTRESPONSE']._serialized_start=374
  _globals['_GENERATEMONTHLYREPORTRESPONSE']._serialized_end=452
  _globals['_EXPORTREPORTREQUEST']._serialized_start=454
  _globals['_EXPORTREPORTREQUEST']._serialized_end=537
  _globals['_EXPORTREPORTRESPONSE']._serialized_start=539
  _globals['_EXPORTREPORTRESPONSE']._serialized_end=595
  _globals['_MSGPACKREPORTRESPONSE']._serialized_start=597
  _globals['_MSGPACKREPORTRESPONSE']._serialized_end=642
  _globals['_REPORTSERVICE']._serialized_start=645
  _globals['_REPORTSERVICE']._serialized_end=981
# @@protoc_insertion_point(module_scope)
